### ISSUE TITLE
JVM issue

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nltk_tutorial#1]
```
>>> twitter = Okt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yyoo/nltk/lib/python3.5/site-packages/konlpy/tag/_okt.py", line 87, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "/home/yyoo/nltk/lib/python3.5/site-packages/konlpy/jvm.py", line 55, in init_jvm
    jvmpath = jvmpath or jpype.getDefaultJVMPath()
  File "/home/yyoo/nltk/lib/python3.5/site-packages/jpype/_core.py", line 121, in get_default_jvm_path
    return finder.get_jvm_path()
  File "/home/yyoo/nltk/lib/python3.5/site-packages/jpype/_jvmfinder.py", line 131, in get_jvm_path
    jvm = method()
  File "/home/yyoo/nltk/lib/python3.5/site-packages/jpype/_jvmfinder.py", line 184, in _get_from_known_locations
    for home in self.find_possible_homes(self._locations):
  File "/home/yyoo/nltk/lib/python3.5/site-packages/jpype/_jvmfinder.py", line 97, in find_possible_homes
    for childname in sorted(os.listdir(parent)):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/jvm'
```

**Comment by ys7yoo** [comment]
Need to install JVM

On Ubuntu,
```
sudo apt-get update
sudo apt-get install default-jre
% sudo apt-get install default-jdk
```

https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

**Comment by ys7yoo** [comment]
On a OSX, you may have errors like the following.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-3958deef6de5> in <module>()
      1 from konlpy.tag import Okt
----> 2 twitter = Okt()
      3 text = '단독입찰보다 복수입찰의 경우'
      4 twitter.pos(text)

~/nltk/lib/python3.6/site-packages/konlpy/tag/_okt.py in __init__(self, jvmpath, max_heap_size)
     89         oktJavaPackage = jpype.JPackage('kr.lucypark.okt')
     90         OktInterfaceJavaClass = oktJavaPackage.OktInterface
---> 91         self.jki = OktInterfaceJavaClass()
     92         self.tagset = utils.read_json('%s/data/tagset/twitter.json' % utils.installpath)

~/nltk/lib/python3.6/site-packages/jpype/_jpackage.py in __call__(self, *arg, **kwarg)
     60 
     61     def __call__(self, *arg, **kwarg):
---> 62         raise TypeError("Package {0} is not Callable".format(self.__name))

TypeError: Package kr.lucypark.okt.OktInterface is not Callable
```

**Comment by ys7yoo** [comment]
You can solve it by Installing JRE.
See README.md
